### ISSUE TITLE
Missing stonecutter cobblestone stair recipe

### ISSUE THREAD

**Issue by ruax2891** [Kyubion-Studios/Grid#2]
There is no recipe for the cobblestone stair using the stonecutter. After I disabled the datapack, it showed up again.
Using Grid v1.9.2.21 (Datapack) on a Minecraft 1.21 Fabric server

EDIT: I've also found out that when putting a block of copper, you can't craft cut copper stairs, only through the crafting table

**Comment by Nearznn** [comment]
Actually, all stairs recipes were missing from the stonecutter.
This is fixed in the latest release, thanks for reporting!
